### ISSUE TITLE
inputとfilterって違いある？

### ISSUE THREAD

**Issue by wtnb75** [wtnb75/filterweb#16]
ほとんど同じだよね…入力をもらうかどうかだけの話で。

**Comment by wtnb75** [comment]
こんなイメージ？ inputとoutputと処理内容を定義できるようにすればいい。

```yaml
endpoints:
- path: /
  method: GET
  status: 200
  headers:
    content-type: text/html
  output:
    headers: {to: src_hdr}
  pipeline:
  - type: http
    url: https://host.name/path
    method: GET
    auth: [hello, world]
    output:
      body: {parse: json, to: var1}
      headers: {to: hdr1}
  - type: jinja2
    template_filename: index.html.j2
    input:
      data: var1
      headers: hdr1
      hostname: src_hdr.host
```
